# Generated by Django 2.0.2 on 2018-04-25 15:27

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_cart_recipeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='upload',
            field=models.FileField(default='SOME STRING', upload_to=cards.models.get_media_file_name_to_upload),
        ),
    ]
